### ISSUE TITLE
Compatibility with wtp

### ISSUE THREAD

**Issue by Tony-Proum** [tesla/m2eclipse-webby#10]
Hi,

I'm facing an issue when using both webby and wtp plugins, it seems, the 'm2e' outputs are not stored in the same folder : webby uses m2e-webby and wtp uses m2e-wtp.

WTP is helpful to edit our web projects, and webby helps to run and debug our application faster. So it may be a good a thing to install both plugins.

Unfortunately this issue make me unable to launch a web application using webby when wtp is installed (m2e  seems to prefer use wtp location instead of the webby one).

**Comment by jvanzyl** [comment]
The two plugins are not meant to be installed together, and we definitely don't test them together. Would a configuration that allow setting the output folder in m2e-webby help with your issue? We don't use WTP so it's not something we will likely spend much time testing.

**Comment by Tony-Proum** [comment]
+1 I think it may solve this issue.
