### ISSUE TITLE
Installing Webby on Eclipse Luna

### ISSUE THREAD

**Issue by gwpower** [tesla/m2eclipse-webby#11]
Hi, 

I have been trying to use the install URL: http://repository.takari.io:8081/nexus/content/sites/m2e.extras/m2eclipse-webby/0.2.2/N/

I keep getting "unable to read repository" and I am running Eclipse Luna

Is there a different address for this? or a working package that I could add to the 'dropins' directory?

Thanks,

-Greg

**Comment by jvanzyl** [comment]
Yes, use the newer URLs:

https://repository.takari.io/content/sites/m2e.extras/m2eclipse-webby/

**Comment by gwpower** [comment]
Thanks a lot!

**Comment by ifedorenko** [comment]
Also, make sure to use java 7 or better, java 6 does not support ssl configuration we use at https://repository.takari.io
