### ISSUE TITLE
URL not working

### ISSUE THREAD

**Issue by rafaelbrizola** [tesla/m2eclipse-webby#12]
Hi!

The url http://m2eclipse.sonatype.org/sites/m2e-webby/ is offline.

**Comment by jvanzyl** [comment]
The update sites are here: https://repository.takari.io/content/sites/m2e.extras/m2eclipse-webby

And the latest is here:

https://repository.takari.io/content/sites/m2e.extras/m2eclipse-webby/0.2.2/N/

Where did you see a reference to that link?

**Comment by rafaelbrizola** [comment]
In the front page (https://github.com/tesla/m2eclipse-webby):

![screen shot 2015-05-19 at 10 40 51 pm](https://cloud.githubusercontent.com/assets/599015/7701132/35378254-fe78-11e4-9170-b471ca3c216b.png)

**Comment by jvanzyl** [comment]
Fixed thanks.
