### ISSUE TITLE
Revive the project

### ISSUE THREAD

**Issue by RoiSoleil** [tesla/m2eclipse-webby#20]
I would like to revive this project, and make it work again as planned and keep it regularly released and updated to latest servers versions.

@rkrzewski : Can i have write access to the repository ?

I have some work in my fork : https://github.com/RoiSoleil/m2eclipse-webby

**Comment by rkrzewski** [comment]
Hi @RoiSoleil. It's been years since I last used this software. To be frank I forgot that it ever existed :slightly_smiling_face:
I can't give you write access. You need to get in touch with the owners of https://github.com/tesla/ organization.

**Comment by RoiSoleil** [comment]
Hello @cstamas can you give me write access ?

**Comment by cstamas** [comment]
Howdy, sorry, am not an owner....
@fbricon @busjaeger ?

**Comment by mosabua** [comment]
@jvanzyl might also be able to help .. I am just a member

**Comment by RoiSoleil** [comment]
@fbricon Could you please take a look ?

**Comment by fbricon** [comment]
@RoiSoleil gave you maintainer role

**Comment by RoiSoleil** [comment]
> @RoiSoleil gave you maintainer role

Thx

**Comment by fbricon** [comment]
I strongly suggest you use Github releases to publish your update site, no need for extra secrets and no need to host binaries in a git repo. See https://fbricon.github.io/posts/use-github-releases-as-p2-repo/

**Comment by RoiSoleil** [comment]
> I strongly suggest you use Github releases to publish your update site, no need for extra secrets and no need to host binaries in a git repo. See https://fbricon.github.io/posts/use-github-releases-as-p2-repo/

Nice ! Thx for the trick. I will do that way ;) Sorry to disturb you.
